INSERT INTO Courses (course_name, course_code) VALUES ('Entrepreneurship and business development', 'CHE 458');
INSERT INTO Courses (course_name, course_code) VALUES ('Basic Electronics', 'COE 152');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to IT', 'COE 158');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital systems design I', 'COE 272');
INSERT INTO Courses (course_name, course_code) VALUES ('Circuit theory', 'COE 288');
INSERT INTO Courses (course_name, course_code) VALUES ('Operating Systems', 'COE 354');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to software engineering', 'COE 356');
INSERT INTO Courses (course_name, course_code) VALUES ('Embedded Systems', 'COE 358');
INSERT INTO Courses (course_name, course_code) VALUES ('Database and information retrieval', 'COE 368');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital System Design II', 'COE 372');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital Computer Design', 'COE 382');
INSERT INTO Courses (course_name, course_code) VALUES ('Secure network systems', 'COE 456');
INSERT INTO Courses (course_name, course_code) VALUES ('Robotics and computer vision', 'COE 458');
INSERT INTO Courses (course_name, course_code) VALUES ('Fault Diagnosis and Failure tolerance', 'COE 480');
INSERT INTO Courses (course_name, course_code) VALUES ('Industrial Automatic Control', 'COE 484');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to VSLI', 'COE 486');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to financial accounting', 'CSM 158');
INSERT INTO Courses (course_name, course_code) VALUES ('Elements of Economics II', 'ECON 152');
INSERT INTO Courses (course_name, course_code) VALUES ('Basic Electronics', 'EE 152');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Engineering Drawing', 'EE 156');
INSERT INTO Courses (course_name, course_code) VALUES ('Electromechanical Energy and Transformers', 'EE 162');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Machines', 'EE 172');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Measurement and Instrumentation', 'EE 188');
INSERT INTO Courses (course_name, course_code) VALUES ('Synchronous Machines', 'EE 262');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital System', 'EE 272');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Measurement and Instrumentation', 'EE 288');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Engineering Laboratory II', 'EE 292');
INSERT INTO Courses (course_name, course_code) VALUES ('High Voltage Engineering', 'EE 360');
INSERT INTO Courses (course_name, course_code) VALUES ('Substation & Transmission Line Design', 'EE 362');
INSERT INTO Courses (course_name, course_code) VALUES ('Power Electronics', 'EE 366');
INSERT INTO Courses (course_name, course_code) VALUES ('Power System analysis', 'EE 368');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital Control Systems', 'EE 380');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Engineering Laboratory III', 'EE 392');
INSERT INTO Courses (course_name, course_code) VALUES ('Electric Drives', 'EE 462');
INSERT INTO Courses (course_name, course_code) VALUES ('Power System Plan and Optimization', 'EE 466');
INSERT INTO Courses (course_name, course_code) VALUES ('Power systems protection', 'EE 468');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital Signal Processing', 'EE 472');
INSERT INTO Courses (course_name, course_code) VALUES ('System Programming', 'EE 482');
INSERT INTO Courses (course_name, course_code) VALUES ('Communication Skills', 'ENGL 158');
INSERT INTO Courses (course_name, course_code) VALUES ('Literature in English', 'ENGL 264');
INSERT INTO Courses (course_name, course_code) VALUES ('Calculus with analysis', 'MATH 152');
INSERT INTO Courses (course_name, course_code) VALUES ('Mathematics II', 'MATH 152');
INSERT INTO Courses (course_name, course_code) VALUES ('Calculus with several variables', 'MATH 252');
INSERT INTO Courses (course_name, course_code) VALUES ('Mathematics IV', 'MATH 252');
INSERT INTO Courses (course_name, course_code) VALUES ('Engineering drawing', 'ME 160');
INSERT INTO Courses (course_name, course_code) VALUES ('Basic Electronics', 'ME 162');
INSERT INTO Courses (course_name, course_code) VALUES ('Statics of Solid Mechanics', 'ME 164');
INSERT INTO Courses (course_name, course_code) VALUES ('Applied Thermodynamics', 'ME 166');
INSERT INTO Courses (course_name, course_code) VALUES ('Computer Programming for Engineers', 'ME 168');
INSERT INTO Courses (course_name, course_code) VALUES ('Fluid dynamics I', 'ME 252');
INSERT INTO Courses (course_name, course_code) VALUES ('Electrical Engineering Machines', 'ME 252');
INSERT INTO Courses (course_name, course_code) VALUES ('Mechanism Synthesis and analysis I', 'ME 264');
INSERT INTO Courses (course_name, course_code) VALUES ('Thermodynamics I', 'ME 266');
INSERT INTO Courses (course_name, course_code) VALUES ('Manufacturing Technology', 'ME 270');
INSERT INTO Courses (course_name, course_code) VALUES ('Fluid Dynamics', 'ME 352');
INSERT INTO Courses (course_name, course_code) VALUES ('Strength of Materials II', 'ME 356');
INSERT INTO Courses (course_name, course_code) VALUES ('Vibrations', 'ME 362');
INSERT INTO Courses (course_name, course_code) VALUES ('Heat Transfer', 'ME 366');
INSERT INTO Courses (course_name, course_code) VALUES ('Machine Design', 'ME 374');
INSERT INTO Courses (course_name, course_code) VALUES ('Industrial Engineering and Economics', 'ME 392');
INSERT INTO Courses (course_name, course_code) VALUES ('Mechanical Engineering Lab IV', 'ME 396');
INSERT INTO Courses (course_name, course_code) VALUES ('Fluid machinery', 'ME 452');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to finite element', 'ME 456');
INSERT INTO Courses (course_name, course_code) VALUES ('Mechanism synthesis and analysis', 'ME 462');
INSERT INTO Courses (course_name, course_code) VALUES ('Instrumentation', 'ME 464');
INSERT INTO Courses (course_name, course_code) VALUES ('Internal Combustion engines', 'ME 468');
INSERT INTO Courses (course_name, course_code) VALUES ('Machine shop and factory design', 'ME 472');
INSERT INTO Courses (course_name, course_code) VALUES ('Production planning and control', 'ME 474');
INSERT INTO Courses (course_name, course_code) VALUES ('Design of vehicle structures', 'ME 476');
INSERT INTO Courses (course_name, course_code) VALUES ('Production  Engineering II', 'ME 478');
INSERT INTO Courses (course_name, course_code) VALUES ('Mechanical Engineering Materials', 'ME 482');
INSERT INTO Courses (course_name, course_code) VALUES ('Entrepreneurship Development', 'ME 492');
INSERT INTO Courses (course_name, course_code) VALUES ('Maintenance engineering', 'ME 494');
INSERT INTO Courses (course_name, course_code) VALUES ('Human factors and ergonomics', 'ME 496');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to Petroleum Engineering', 'PE 154');
INSERT INTO Courses (course_name, course_code) VALUES ('Physical Chemistry for Engineers', 'PE 156');
INSERT INTO Courses (course_name, course_code) VALUES ('Heat Transport Process', 'PE 252');
INSERT INTO Courses (course_name, course_code) VALUES ('Regional Geology', 'PE 256');
INSERT INTO Courses (course_name, course_code) VALUES ('Petroleum Engineering Thermodynamics II', 'PE 258');
INSERT INTO Courses (course_name, course_code) VALUES ('Reservoir fluid properties', 'PE 260');
INSERT INTO Courses (course_name, course_code) VALUES ('Computer Programming in Oil and Gas', 'PE 262');
INSERT INTO Courses (course_name, course_code) VALUES ('Principles of Land Surveying', 'PE 264');
INSERT INTO Courses (course_name, course_code) VALUES ('Numerical Methods for Petroleum Engineers', 'PE 350');
INSERT INTO Courses (course_name, course_code) VALUES ('Petroleum Geology', 'PE 352');
INSERT INTO Courses (course_name, course_code) VALUES ('Drilling Engineering II', 'PE 354');
INSERT INTO Courses (course_name, course_code) VALUES ('Petroleum Engineering Lab II', 'PE 356');
INSERT INTO Courses (course_name, course_code) VALUES ('Petroleum Production Engineering II', 'PE 358');
INSERT INTO Courses (course_name, course_code) VALUES ('Well Testing', 'PE 360');
INSERT INTO Courses (course_name, course_code) VALUES ('Geostatics', 'PE 362');
INSERT INTO Courses (course_name, course_code) VALUES ('Oil & Gas Geophysics', 'PE 364');
INSERT INTO Courses (course_name, course_code) VALUES ('Health, Safety and Environment', 'PE 366');
INSERT INTO Courses (course_name, course_code) VALUES ('Reservoir recovery techniques', 'PE 450');
INSERT INTO Courses (course_name, course_code) VALUES ('Petroleum project  evaluation', 'PE 452');
INSERT INTO Courses (course_name, course_code) VALUES ('Well completion and stimulation', 'PE 456');
INSERT INTO Courses (course_name, course_code) VALUES ('Oilfeild geochemistry', 'PE 458');
INSERT INTO Courses (course_name, course_code) VALUES ('Refining process technology', 'PE 464');
INSERT INTO Courses (course_name, course_code) VALUES ('Fundamentals of petroleum law', 'PE 466');
INSERT INTO Courses (course_name, course_code) VALUES ('Petroleum Business', 'PE 468');
INSERT INTO Courses (course_name, course_code) VALUES ('Natural Gas engineering', 'PE 472');
INSERT INTO Courses (course_name, course_code) VALUES ('Pipeline Engineering', 'PE 474');
INSERT INTO Courses (course_name, course_code) VALUES ('Energy and climate change', 'PE 476');
INSERT INTO Courses (course_name, course_code) VALUES ('General Physics', 'PHY 170');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to Psychology', 'PSYC 154');
INSERT INTO Courses (course_name, course_code) VALUES ('Engineering research and technical report', 'TE 152');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to Communication Networks', 'TE 156');
INSERT INTO Courses (course_name, course_code) VALUES ('Introduction to Programming I', 'TE 158 ');
INSERT INTO Courses (course_name, course_code) VALUES ('Electromagnetic fields', 'TE 262');
INSERT INTO Courses (course_name, course_code) VALUES ('Telecommunication Infrastructure', 'TE 362');
INSERT INTO Courses (course_name, course_code) VALUES ('Communication circuits', 'TE 364');
INSERT INTO Courses (course_name, course_code) VALUES ('Antennas and Propagation', 'TE 372');
INSERT INTO Courses (course_name, course_code) VALUES ('Data Communication Networks', 'TE 382');
INSERT INTO Courses (course_name, course_code) VALUES ('Switching Engineering in communication', 'TE 384');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital communication systems', 'TE 386');
INSERT INTO Courses (course_name, course_code) VALUES ('Telecommunication Policy', 'TE 462');
INSERT INTO Courses (course_name, course_code) VALUES ('Digital signal processing', 'EE 472');
INSERT INTO Courses (course_name, course_code) VALUES ('Mobile and satellite communication system', 'TE 472');
INSERT INTO Courses (course_name, course_code) VALUES ('Microwave Engineering', 'TE 474');
INSERT INTO Courses (course_name, course_code) VALUES ('Network Planning', 'TE 484');