INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Abdul ahman Ahmed', 'abdulahmed@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Abu Frimpong Solomon', 'abusolomon@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Acheampong Francisca Adoma', 'acheampongadoma@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Acquah Isaac', 'acquahisaac@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adam Faisal Wahab', 'adamwahab@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Addo Emmanuel Obuobi Kwame', 'addokwame@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adenutsi Caspar Daniel', 'adenutsidaniel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adjaidoo Samuella Theresa', 'adjaidootheresa@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adjei Eunice Akyereko', 'adjeiakyereko@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adjei Samuel', 'adjeisamuel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adjei Stephen', 'adjeistephen@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Adrah Charles Mawutor', 'adrahmawutor@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Affum Emmanuel Ampoma', 'affumampoma@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Agbemenu Andrew Selasi', 'agbemenuselasi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Agyekum Agyeman Prempeh', 'agyekumprempeh@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Agyekum Kwame Agyeman', 'agyekumagyeman@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Agyeman Justice Owusu', 'agyemanowusu@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Akowuah Emmanuel Kofi', 'akowuahkofi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Alhassan Yakubu', 'alhassanyakubu@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Amoabeng Kofi Owura', 'amoabengowura@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Amoah Enoch Kwabena', 'amoahkwabena@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Ampofo Joshua', 'ampofojoshua@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Andoh Prince Yaw', 'andohyaw@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Antoh Emmanuel Kwaku', 'antohkwaku@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Asante Comas Yaw', 'asanteyaw@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Asigri Peter', 'asigripeter@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Asamoah Boateng Kenneth', 'asamoahkenneth@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Boaben Samuel', 'boabensamuel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Boagye-Agyeman Candy', 'boagye-agyemancandy@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Boakye Agyeman Candy', 'boakyecandy@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Boateng Cyril Dziedzorm', 'boatengdziedzorm@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Boateng Kwame Osei', 'boatengosei@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Boateng Maxwell Akwasi', 'boatengakwasi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Borkloe Julius Kwame', 'borkloekwame@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Buabeng Emmanuel', 'buabengemmanuel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Casper Daniel', 'casperdaniel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Casper Adenutsi', 'casperadenutsi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Dzebre Dennis Kwame Edem', 'dzebreedem@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Davis Francis', 'davisfrancis@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Eghan Rhydal Esi', 'eghanesi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Ellis Sani Mubarak', 'ellismubarak@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Effah Francis Boafo', 'effahboafo@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Erzuah Daniel', 'erzuahdaniel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Erzuah Samuel', 'erzuahsamuel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Ezearn Jeffery', 'ezearnjeffery@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Fiagbe Yesuenyeagbe Atsu Kwabla', 'fiagbekwabla@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Forson Francis Kofi', 'forsonkofi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Frimpong Emmanuel Assuming', 'frimpongassuming@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Gadze James Dzisi', 'gadzedzisi@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Keelson Eliel', 'keelsoneliel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Klogo Griffith Selorm', 'klogoselorm@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Kommey Benjamin', 'kommeybenjamin@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Kponyo Jerry John', 'kponyojohn@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Kwabi Prince Amponsah', 'kwabiamponsah@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Kwao Boateng Emmanuela', 'kwaoemmanuela@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Kwasi Sarfo Adu', 'kwasiadu@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Kwegyir Daniel', 'kwegyirdaniel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Marfo William Apau', 'marfoapau@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Mensah Lena Dzifa', 'mensahdzifa@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Nunoo Mensah Henry', 'nunoohenry@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Obeng George Yaw', 'obengyaw@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Obeng Gyasi Kwame', 'obengkwame@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Obeng Kwakye Kingsford', 'obengkingsford@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Obuor Agyekum Opuni Boakye', 'obuorboakye@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Opare Kwasi Adu Boahen', 'opareboahen@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Opoku Daniel', 'opokudaniel@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Opoku Richard', 'opokurichard@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Oppong Tawiah Peter', 'oppongpeter@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Okyere Philip Yaw', 'okyereyaw@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Osei Danso Harriet Efua', 'oseiefua@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Owusu Ansah Ernest', 'owusuernest@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Owusu Richard', 'owusurichard@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Quansah David Ato', 'quansahato@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Quaye Jonathan Atuquaye', 'quayeatuquaye@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('R.N Borkor', 'r.nborkor@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Sackey Samuel Mensah', 'sackeymensah@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Sarfo Fordjour Elizabeth', 'sarfoelizabeth@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Sarkodie Kwame', 'sarkodiekwame@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Sekyere Charles Kofi Kafui', 'sekyerekafui@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Sokama Neuyam Yen Adams', 'sokamaadams@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Takyi Paul Owusu', 'takyiowusu@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Tay Godwin Fabiola Kwaku', 'taykwaku@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Tchao Eric Tutu', 'tchaotutu@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Twumasi Elvis', 'twumasielvis@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Wireko Frederick Asenso', 'wirekoasenso@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Yeboah Akowuah Bright', 'yeboahbright@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Yeboah Edward', 'yeboahedward@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Yeboah Philomena Ama Okyeso', 'yeboahokyeso@gmail.com');
INSERT INTO Lecturers (lecturer_name, lecturer_email) VALUES ('Y.E Ayekple', 'y.eayekple@gmail.com');